name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build FirstApp
      if: ${{ contains(github.event.head_commit.modified, 'FirstApp/') }}
      run: |
        cd FirstApp
        docker build -t firstapp:latest .
        cat ~/my_password.txt | docker login --username mallikharjun999 --password-stdin
        docker image tag firstapp:latest mallikharjun999/codesense:${{ steps.buildnumber.outputs.build_number }}
        docker push mallikharjun999/codesense:${{ steps.buildnumber.outputs.build_number }}

    - name: Build SecondApp
      if: ${{ contains(github.event.head_commit.modified, 'SecondApp/') }}
      run: |
        cd SecondApp
        docker build -t secondapp:${{ steps.buildnumber.outputs.build_number }} .
        cat ~/my_password.txt | docker login --username mallikharjun999 --password-stdin
        docker image tag firstapp:${{ steps.buildnumber.outputs.build_number }} mallikharjun999/codesense
        docker push mallikharjun999/codesense

    - name: Build FirstApp and SecondApp
      if: ${{ contains(github.event.head_commit.modified, 'Modules/') }}
      run: |
        cd FirstApp
        docker build -t firstapp:${{ steps.buildnumber.outputs.build_number }} .
        cat ~/my_password.txt | docker login --username mallikharjun999 --password-stdin
        docker image tag firstapp:${{ steps.buildnumber.outputs.build_number }} mallikharjun999/codesense
        docker push mallikharjun999/codesense

        cd ../SecondApp
        docker build -t secondapp:${{ steps.buildnumber.outputs.build_number }} .
        cat ~/my_password.txt | docker login --username mallikharjun999 --password-stdin
        docker image tag firstapp:${{ steps.buildnumber.outputs.build_number }} mallikharjun999/codesense
        docker push mallikharjun999/codesense