name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build FirstApp
        if: 'contains(github.event.head_commit.modified, FirstApp ) || contains(github.event.head_commit.added, FirstApp )'    
        run: |
          cd FirstApp
          cp -R ../Modules .
          # Additional build steps for FirstApp

      - name: Build SecondApp
        if: 'contains( github.event.head_commit.modified,"SecondApp" ) || contains( github.event.head_commit.added,"SecondApp" )'
        run: |
          cd SecondApp
          cp -R ../Modules .
          # Additional build steps for SecondApp

      - name: Build Both Apps
        if: 'contains( github.event.head_commit.modified,"Modules" ) || contains( github.event.head_commit.added,"Modules" )'
        run: |
          cd FirstApp
          cp -R ../Modules .
          # Additional build steps for FirstApp

          cd ../SecondApp
          cp -R ../Modules .
          # Additional build steps for SecondApp
 
      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/my-app:${{ github.sha }}
