name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build FirstApp
      if: ${{ contains(github.event.head_commit.modified, 'FirstApp/') }}
      run: |
        cd FirstApp
        docker build -t firstapp:${{ github.sha }} .
        docker push mallikharjun999/firstapp:${{ github.sha }}

    - name: Build SecondApp
      if: ${{ contains(github.event.head_commit.modified, 'SecondApp/') }}
      run: |
        cd SecondApp
        docker build -t secondapp:${{ github.sha }} .
        docker push mallikharjun999/secondapp:${{ github.sha }}

    - name: Build FirstApp and SecondApp
      if: ${{ contains(github.event.head_commit.modified, 'Modules/') }}
      run: |
        cd FirstApp
        docker build -t ghcr.io/<username>/firstapp:${{ github.sha }} .
        docker push mallikharjun999/firstapp:${{ github.sha }}

        cd ../SecondApp
        docker build -t ghcr.io/<username>/secondapp:${{ github.sha }} .
        docker push mallikharjun999/secondapp:${{ github.sha }}